### ISSUE TITLE
Aufgabenteilung

### ISSUE THREAD

**Issue by pv42** [pv42/Assignment3_DS#1]
Ich habe die grundlegende Projektstuktur erstellt (leere Klasse/Methoden):
- Arc (Graphkante) ez
- CSVLoader(soll csv Dateien lesen/laden)
- Graph (der gesamte Graph) ez
- Main (Hauptklasse)
- Node (Graphknoten) ez
- Path (Weg im Graphen) ez
- Pathfinder (Klasse zum finden des kürzesten Weg im Graphen)

Beachtet :
- Jeder sollte mindestens 1 Klasse bearbeiten.
- Mit ez markierte Klassen sind sehr einfach, da sie fast ausschließlich trivialen Code enthalten, erwartet keine Hilfe von mir wenn ihr so eine Klasse wählt.
- Bereitsvorhanden Methoden sollen nicht 0/null zurückgeben sondern das tun was im Kommentar über ihnen berschieben ist oder ihr Name aussagt, d.h. diese Methoden müssen implementiert werden, wenn ihr z.B. Main bearbeitet könnt ihr euch also auf deren existens und Funktionalität verlassen.
- Jede nicht private Methode und jede Klasse sollte ein Javadoc-Kommentar haben
- Alle anderen Methoden sollten mindestens minimal kommentiert sein !

Ihr könnt in den Kommentaren schreiben was ihr machen möchtet.

**Comment by Sebastian-Neubert** [comment]
Ich würde mich um den CSVLoader kümmern

**Comment by NolteS** [comment]
Ich nehm den Path

**Comment by fuck-o-f-f** [comment]
Ich versuche mich an den Node

**Comment by HSporys** [comment]
ich arc

**Comment by martin-krebs** [comment]
Graph
